#include <iostream>

int main() {
    try {
        try {
            throw 20;
        } catch (int n) {
            std::cout << "Handle Partially: " << n << std::endl;
            throw; // Rethrow exception
        }
    } catch (int n) {
        std::cout << "Handle Remaining: " << n << std::endl;
    }
    return 0;
}
